name: ckan2pycsw
services:
  pycsw:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/mjanez/ckan-pycsw:latest
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
          max-size: "100m"
          max-file: "10"
    ports:
      - "0.0.0.0:${PYCSW_PORT}:${PYCSW_PORT}"
    volumes:
        - ./log:${APP_DIR}/log
        - ./metadata:${APP_DIR}/metadata
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "http://localhost:${PYCSW_PORT}"]
networks:
  default:
    name: ckan2pycsw_default