name: ckan2pycsw
services:
  pycsw:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
          max-size: "100m"
          max-file: "10"
    ports:
      - "0.0.0.0:${PYCSW_PORT}:${PYCSW_PORT}"
      # debugpy
      - "5678:5678"
    volumes:
        - ./log:${APP_DIR}/log
        - ./metadata:${APP_DIR}/metadata
networks:
  default:
    name: ckan2pycsw_default